// Comprehensive list of US universities
export const universities = [
  'Arizona State University',
  'University of Arizona',
  'Auburn University',
  'University of Alabama',
  'University of Alabama at Birmingham',
  'University of Alaska Anchorage',
  'University of Arkansas',
  'Arkansas State University',
  'Boston University',
  'Boston College',
  'Brandeis University',
  'Brown University',
  'Brigham Young University',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of California, Irvine',
  'University of California, Davis',
  'University of California, Santa Barbara',
  'University of California, Santa Cruz',
  'University of California, Riverside',
  'University of California, Merced',
  'California Institute of Technology',
  'California State University, Long Beach',
  'California State University, Fullerton',
  'San Diego State University',
  'San Francisco State University',
  'San Jose State University',
  'University of Colorado Boulder',
  'Colorado State University',
  'University of Denver',
  'University of Connecticut',
  'Yale University',
  'University of Delaware',
  'Delaware State University',
  'American University',
  'George Washington University',
  'Georgetown University',
  'Howard University',
  'University of Florida',
  'Florida State University',
  'University of Miami',
  'University of Central Florida',
  'University of South Florida',
  'Florida International University',
  'Florida Atlantic University',
  'University of Georgia',
  'Georgia Institute of Technology',
  'Emory University',
  'Georgia State University',
  'University of Hawaii at Manoa',
  'University of Idaho',
  'Boise State University',
  'University of Illinois Urbana-Champaign',
  'Northwestern University',
  'University of Chicago',
  'Illinois Institute of Technology',
  'DePaul University',
  'Loyola University Chicago',
  'Indiana University Bloomington',
  'Purdue University',
  'University of Notre Dame',
  'Butler University',
  'Ball State University',
  'University of Iowa',
  'Iowa State University',
  'University of Kansas',
  'Kansas State University',
  'University of Kentucky',
  'University of Louisville',
  'Western Kentucky University',
  'Louisiana State University',
  'Tulane University',
  'University of New Orleans',
  'University of Maine',
  'University of Maryland, College Park',
  'Johns Hopkins University',
  'University of Maryland, Baltimore County',
  'Towson University',
  'Harvard University',
  'Massachusetts Institute of Technology',
  'Tufts University',
  'University of Massachusetts Amherst',
  'University of Massachusetts Boston',
  'Northeastern University',
  'University of Michigan',
  'Michigan State University',
  'Wayne State University',
  'Western Michigan University',
  'University of Minnesota Twin Cities',
  'University of Mississippi',
  'Mississippi State University',
  'University of Missouri',
  'Washington University in St. Louis',
  'Missouri University of Science and Technology',
  'University of Montana',
  'Montana State University',
  'University of Nebraska-Lincoln',
  'Creighton University',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of New Hampshire',
  'Dartmouth College',
  'Rutgers University',
  'Princeton University',
  'New Jersey Institute of Technology',
  'Rowan University',
  'University of New Mexico',
  'New Mexico State University',
  'Columbia University',
  'Cornell University',
  'New York University',
  'University of Rochester',
  'Syracuse University',
  'Stony Brook University',
  'University at Buffalo',
  'Binghamton University',
  'Rensselaer Polytechnic Institute',
  'Fordham University',
  'Hofstra University',
  'University of North Carolina at Chapel Hill',
  'Duke University',
  'North Carolina State University',
  'Wake Forest University',
  'UNC Charlotte',
  'East Carolina University',
  'University of North Dakota',
  'North Dakota State University',
  'Ohio State University',
  'Case Western Reserve University',
  'University of Cincinnati',
  'Ohio University',
  'Miami University',
  'Kent State University',
  'University of Oklahoma',
  'Oklahoma State University',
  'University of Tulsa',
  'University of Oregon',
  'Oregon State University',
  'Portland State University',
  'Pennsylvania State University',
  'University of Pennsylvania',
  'Carnegie Mellon University',
  'University of Pittsburgh',
  'Temple University',
  'Drexel University',
  'Villanova University',
  'Lehigh University',
  'Brown University',
  'University of Rhode Island',
  'Clemson University',
  'University of South Carolina',
  'College of Charleston',
  'South Dakota State University',
  'University of South Dakota',
  'University of Tennessee, Knoxville',
  'Vanderbilt University',
  'University of Memphis',
  'Middle Tennessee State University',
  'University of Texas at Austin',
  'Texas A&M University',
  'Rice University',
  'University of Houston',
  'Texas Tech University',
  'University of Texas at Dallas',
  'University of Texas at San Antonio',
  'Southern Methodist University',
  'Baylor University',
  'Texas Christian University',
  'University of Utah',
  'Utah State University',
  'Brigham Young University',
  'University of Vermont',
  'University of Virginia',
  'Virginia Tech',
  'College of William & Mary',
  'George Mason University',
  'James Madison University',
  'Old Dominion University',
  'Virginia Commonwealth University',
  'University of Washington',
  'Washington State University',
  'Seattle University',
  'Gonzaga University',
  'Western Washington University',
  'West Virginia University',
  'Marshall University',
  'University of Wisconsin-Madison',
  'Marquette University',
  'University of Wisconsin-Milwaukee',
  'University of Wyoming',
].sort()

export function filterUniversities(query: string): string[] {
  if (!query || query.length < 2) return []
  const lowerQuery = query.toLowerCase()
  return universities.filter((uni) => uni.toLowerCase().includes(lowerQuery)).slice(0, 8)
}
