// Comprehensive US university database with campus support and official favicon URLs

export interface University {
  name: string
  domain: string
  state: string
  city: string
  campus?: string
}

// Get official favicon from university domain
export function getUniversityLogoUrl(domain: string): string {
  // Use Google's favicon service which reliably returns official favicons
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`
}

// Common abbreviations mapping
const abbreviations: Record<string, string> = {
  'mit': 'Massachusetts Institute of Technology',
  'ucla': 'University of California, Los Angeles',
  'ucb': 'University of California, Berkeley',
  'uc berkeley': 'University of California, Berkeley',
  'usc': 'University of Southern California',
  'nyu': 'New York University',
  'bu': 'Boston University',
  'bc': 'Boston College',
  'cmu': 'Carnegie Mellon University',
  'caltech': 'California Institute of Technology',
  'gt': 'Georgia Institute of Technology',
  'gatech': 'Georgia Institute of Technology',
  'uw': 'University of Washington',
  'ut': 'University of Texas at Austin',
  'ut austin': 'University of Texas at Austin',
  'utd': 'University of Texas at Dallas',
  'osu': 'Ohio State University',
  'psu': 'Penn State University',
  'msu': 'Michigan State University',
  'umn': 'University of Minnesota',
  'umd': 'University of Maryland',
  'umich': 'University of Michigan',
  'wisc': 'University of Wisconsin',
  'uiuc': 'University of Illinois Urbana-Champaign',
  'ucsd': 'University of California, San Diego',
  'uci': 'University of California, Irvine',
  'ucsb': 'University of California, Santa Barbara',
  'ucsc': 'University of California, Santa Cruz',
  'ucr': 'University of California, Riverside',
  'ucd': 'University of California, Davis',
  'sfsu': 'San Francisco State University',
  'sdsu': 'San Diego State University',
  'sjsu': 'San Jose State University',
  'csuf': 'California State University, Fullerton',
  'csulb': 'California State University, Long Beach',
  'csun': 'California State University, Northridge',
  'asu': 'Arizona State University',
  'ua': 'University of Arizona',
  'cu': 'University of Colorado',
  'cu boulder': 'University of Colorado Boulder',
  'uf': 'University of Florida',
  'fsu': 'Florida State University',
  'ucf': 'University of Central Florida',
  'fiu': 'Florida International University',
  'uga': 'University of Georgia',
  'tamu': 'Texas A&M University',
  'vt': 'Virginia Tech',
  'uva': 'University of Virginia',
  'unc': 'University of North Carolina at Chapel Hill',
  'duke': 'Duke University',
  'wustl': 'Washington University in St. Louis',
  'washu': 'Washington University in St. Louis',
  'jhu': 'Johns Hopkins University',
  'upenn': 'University of Pennsylvania',
  'penn': 'University of Pennsylvania',
  'cornell': 'Cornell University',
  'brown': 'Brown University',
  'yale': 'Yale University',
  'harvard': 'Harvard University',
  'princeton': 'Princeton University',
  'columbia': 'Columbia University',
  'dartmouth': 'Dartmouth College',
  'stanford': 'Stanford University',
  'rice': 'Rice University',
  'nd': 'University of Notre Dame',
  'notre dame': 'University of Notre Dame',
  'vanderbilt': 'Vanderbilt University',
  'vandy': 'Vanderbilt University',
  'emory': 'Emory University',
  'tulane': 'Tulane University',
  'wfu': 'Wake Forest University',
  'wake': 'Wake Forest University',
  'gw': 'George Washington University',
  'gwu': 'George Washington University',
  'georgetown': 'Georgetown University',
  'american': 'American University',
  'au': 'American University',
  'howard': 'Howard University',
  'umass': 'University of Massachusetts Amherst',
  'uconn': 'University of Connecticut',
  'rutgers': 'Rutgers University',
  'temple': 'Temple University',
  'drexel': 'Drexel University',
  'villanova': 'Villanova University',
  'lehigh': 'Lehigh University',
  'syracuse': 'Syracuse University',
  'rochester': 'University of Rochester',
  'rpi': 'Rensselaer Polytechnic Institute',
  'case': 'Case Western Reserve University',
  'cwru': 'Case Western Reserve University',
  'purdue': 'Purdue University',
  'iu': 'Indiana University',
  'indiana': 'Indiana University',
  'iowa': 'University of Iowa',
  'iowa state': 'Iowa State University',
  'nebraska': 'University of Nebraska',
  'kansas': 'University of Kansas',
  'ku': 'University of Kansas',
  'mizzou': 'University of Missouri',
  'ole miss': 'University of Mississippi',
  'lsu': 'Louisiana State University',
  'bama': 'University of Alabama',
  'auburn': 'Auburn University',
  'tennessee': 'University of Tennessee',
  'kentucky': 'University of Kentucky',
  'sc': 'University of South Carolina',
  'clemson': 'Clemson University',
  'wvu': 'West Virginia University',
  'pitt': 'University of Pittsburgh',
  'penn state': 'Penn State University',
  'buffalo': 'University at Buffalo',
  'stony brook': 'Stony Brook University',
  'binghamton': 'Binghamton University',
  'albany': 'University at Albany',
  'hofstra': 'Hofstra University',
  'fordham': 'Fordham University',
  'depaul': 'DePaul University',
  'loyola': 'Loyola University Chicago',
  'marquette': 'Marquette University',
  'creighton': 'Creighton University',
  'slu': 'Saint Louis University',
  'du': 'University of Denver',
  'gonzaga': 'Gonzaga University',
  'seattle u': 'Seattle University',
  'scu': 'Santa Clara University',
  'lmu': 'Loyola Marymount University',
  'pepperdine': 'Pepperdine University',
  'usd': 'University of San Diego',
  'usf': 'University of San Francisco',
  'smu': 'Southern Methodist University',
  'tcu': 'Texas Christian University',
  'baylor': 'Baylor University',
  'byu': 'Brigham Young University',
  'utah': 'University of Utah',
  'cu denver': 'University of Colorado Denver',
  'unm': 'University of New Mexico',
  'unlv': 'University of Nevada, Las Vegas',
  'unr': 'University of Nevada, Reno',
  'hawaii': 'University of Hawaii',
  'oregon': 'University of Oregon',
  'uo': 'University of Oregon',
  'wsu': 'Washington State University',
  'portland': 'University of Portland',
  'gonzaga': 'Gonzaga University',
}

// Comprehensive university list with official domains
export const universities: University[] = [
  // Ivy League
  { name: 'Harvard University', domain: 'harvard.edu', state: 'MA', city: 'Cambridge' },
  { name: 'Yale University', domain: 'yale.edu', state: 'CT', city: 'New Haven' },
  { name: 'Princeton University', domain: 'princeton.edu', state: 'NJ', city: 'Princeton' },
  { name: 'Columbia University', domain: 'columbia.edu', state: 'NY', city: 'New York' },
  { name: 'University of Pennsylvania', domain: 'upenn.edu', state: 'PA', city: 'Philadelphia' },
  { name: 'Brown University', domain: 'brown.edu', state: 'RI', city: 'Providence' },
  { name: 'Dartmouth College', domain: 'dartmouth.edu', state: 'NH', city: 'Hanover' },
  { name: 'Cornell University', domain: 'cornell.edu', state: 'NY', city: 'Ithaca' },

  // Top Private Universities
  { name: 'Stanford University', domain: 'stanford.edu', state: 'CA', city: 'Stanford' },
  { name: 'Massachusetts Institute of Technology', domain: 'mit.edu', state: 'MA', city: 'Cambridge' },
  { name: 'California Institute of Technology', domain: 'caltech.edu', state: 'CA', city: 'Pasadena' },
  { name: 'Duke University', domain: 'duke.edu', state: 'NC', city: 'Durham' },
  { name: 'Northwestern University', domain: 'northwestern.edu', state: 'IL', city: 'Evanston' },
  { name: 'University of Chicago', domain: 'uchicago.edu', state: 'IL', city: 'Chicago' },
  { name: 'Johns Hopkins University', domain: 'jhu.edu', state: 'MD', city: 'Baltimore' },
  { name: 'Rice University', domain: 'rice.edu', state: 'TX', city: 'Houston' },
  { name: 'Vanderbilt University', domain: 'vanderbilt.edu', state: 'TN', city: 'Nashville' },
  { name: 'Washington University in St. Louis', domain: 'wustl.edu', state: 'MO', city: 'St. Louis' },
  { name: 'Emory University', domain: 'emory.edu', state: 'GA', city: 'Atlanta' },
  { name: 'Georgetown University', domain: 'georgetown.edu', state: 'DC', city: 'Washington' },
  { name: 'University of Notre Dame', domain: 'nd.edu', state: 'IN', city: 'Notre Dame' },
  { name: 'Carnegie Mellon University', domain: 'cmu.edu', state: 'PA', city: 'Pittsburgh' },
  { name: 'University of Southern California', domain: 'usc.edu', state: 'CA', city: 'Los Angeles' },
  { name: 'New York University', domain: 'nyu.edu', state: 'NY', city: 'New York' },
  { name: 'Boston University', domain: 'bu.edu', state: 'MA', city: 'Boston' },
  { name: 'Boston College', domain: 'bc.edu', state: 'MA', city: 'Chestnut Hill' },
  { name: 'Tufts University', domain: 'tufts.edu', state: 'MA', city: 'Medford' },
  { name: 'Northeastern University', domain: 'northeastern.edu', state: 'MA', city: 'Boston' },
  { name: 'Brandeis University', domain: 'brandeis.edu', state: 'MA', city: 'Waltham' },
  { name: 'George Washington University', domain: 'gwu.edu', state: 'DC', city: 'Washington' },
  { name: 'American University', domain: 'american.edu', state: 'DC', city: 'Washington' },
  { name: 'Howard University', domain: 'howard.edu', state: 'DC', city: 'Washington' },
  { name: 'University of Miami', domain: 'miami.edu', state: 'FL', city: 'Coral Gables' },
  { name: 'University of Rochester', domain: 'rochester.edu', state: 'NY', city: 'Rochester' },
  { name: 'Case Western Reserve University', domain: 'case.edu', state: 'OH', city: 'Cleveland' },
  { name: 'Tulane University', domain: 'tulane.edu', state: 'LA', city: 'New Orleans' },
  { name: 'Wake Forest University', domain: 'wfu.edu', state: 'NC', city: 'Winston-Salem' },
  { name: 'Lehigh University', domain: 'lehigh.edu', state: 'PA', city: 'Bethlehem' },
  { name: 'Villanova University', domain: 'villanova.edu', state: 'PA', city: 'Villanova' },
  { name: 'Rensselaer Polytechnic Institute', domain: 'rpi.edu', state: 'NY', city: 'Troy' },
  { name: 'Syracuse University', domain: 'syracuse.edu', state: 'NY', city: 'Syracuse' },
  { name: 'Fordham University', domain: 'fordham.edu', state: 'NY', city: 'New York' },
  { name: 'Drexel University', domain: 'drexel.edu', state: 'PA', city: 'Philadelphia' },
  { name: 'Temple University', domain: 'temple.edu', state: 'PA', city: 'Philadelphia' },
  { name: 'Southern Methodist University', domain: 'smu.edu', state: 'TX', city: 'Dallas' },
  { name: 'Texas Christian University', domain: 'tcu.edu', state: 'TX', city: 'Fort Worth' },
  { name: 'Baylor University', domain: 'baylor.edu', state: 'TX', city: 'Waco' },
  { name: 'Brigham Young University', domain: 'byu.edu', state: 'UT', city: 'Provo' },
  { name: 'Pepperdine University', domain: 'pepperdine.edu', state: 'CA', city: 'Malibu' },
  { name: 'Santa Clara University', domain: 'scu.edu', state: 'CA', city: 'Santa Clara' },
  { name: 'Loyola Marymount University', domain: 'lmu.edu', state: 'CA', city: 'Los Angeles' },
  { name: 'University of San Diego', domain: 'sandiego.edu', state: 'CA', city: 'San Diego' },
  { name: 'University of San Francisco', domain: 'usfca.edu', state: 'CA', city: 'San Francisco' },
  { name: 'DePaul University', domain: 'depaul.edu', state: 'IL', city: 'Chicago' },
  { name: 'Loyola University Chicago', domain: 'luc.edu', state: 'IL', city: 'Chicago' },
  { name: 'Illinois Institute of Technology', domain: 'iit.edu', state: 'IL', city: 'Chicago' },
  { name: 'Marquette University', domain: 'marquette.edu', state: 'WI', city: 'Milwaukee' },
  { name: 'Creighton University', domain: 'creighton.edu', state: 'NE', city: 'Omaha' },
  { name: 'Saint Louis University', domain: 'slu.edu', state: 'MO', city: 'St. Louis' },
  { name: 'University of Denver', domain: 'du.edu', state: 'CO', city: 'Denver' },
  { name: 'University of Tulsa', domain: 'utulsa.edu', state: 'OK', city: 'Tulsa' },
  { name: 'Stevens Institute of Technology', domain: 'stevens.edu', state: 'NJ', city: 'Hoboken' },
  { name: 'Worcester Polytechnic Institute', domain: 'wpi.edu', state: 'MA', city: 'Worcester' },
  { name: 'Rochester Institute of Technology', domain: 'rit.edu', state: 'NY', city: 'Rochester' },
  { name: 'Georgia Institute of Technology', domain: 'gatech.edu', state: 'GA', city: 'Atlanta' },
  { name: 'George Mason University', domain: 'gmu.edu', state: 'VA', city: 'Fairfax' },
  { name: 'Hofstra University', domain: 'hofstra.edu', state: 'NY', city: 'Hempstead' },
  { name: 'The New School', domain: 'newschool.edu', state: 'NY', city: 'New York' },
  { name: 'Clarkson University', domain: 'clarkson.edu', state: 'NY', city: 'Potsdam' },
  { name: 'Adelphi University', domain: 'adelphi.edu', state: 'NY', city: 'Garden City' },
  { name: 'University of the Pacific', domain: 'pacific.edu', state: 'CA', city: 'Stockton' },
  { name: 'Chapman University', domain: 'chapman.edu', state: 'CA', city: 'Orange' },
  { name: 'Gonzaga University', domain: 'gonzaga.edu', state: 'WA', city: 'Spokane' },
  { name: 'Seattle University', domain: 'seattleu.edu', state: 'WA', city: 'Seattle' },
  { name: 'University of Portland', domain: 'up.edu', state: 'OR', city: 'Portland' },
  { name: 'Butler University', domain: 'butler.edu', state: 'IN', city: 'Indianapolis' },
  { name: 'Xavier University', domain: 'xavier.edu', state: 'OH', city: 'Cincinnati' },
  { name: 'University of Dayton', domain: 'udayton.edu', state: 'OH', city: 'Dayton' },

  // University of California System
  { name: 'University of California, Berkeley', domain: 'berkeley.edu', state: 'CA', city: 'Berkeley', campus: 'Berkeley' },
  { name: 'University of California, Los Angeles', domain: 'ucla.edu', state: 'CA', city: 'Los Angeles', campus: 'Los Angeles' },
  { name: 'University of California, San Diego', domain: 'ucsd.edu', state: 'CA', city: 'La Jolla', campus: 'San Diego' },
  { name: 'University of California, Santa Barbara', domain: 'ucsb.edu', state: 'CA', city: 'Santa Barbara', campus: 'Santa Barbara' },
  { name: 'University of California, Irvine', domain: 'uci.edu', state: 'CA', city: 'Irvine', campus: 'Irvine' },
  { name: 'University of California, Davis', domain: 'ucdavis.edu', state: 'CA', city: 'Davis', campus: 'Davis' },
  { name: 'University of California, Santa Cruz', domain: 'ucsc.edu', state: 'CA', city: 'Santa Cruz', campus: 'Santa Cruz' },
  { name: 'University of California, Riverside', domain: 'ucr.edu', state: 'CA', city: 'Riverside', campus: 'Riverside' },
  { name: 'University of California, Merced', domain: 'ucmerced.edu', state: 'CA', city: 'Merced', campus: 'Merced' },
  { name: 'University of California, San Francisco', domain: 'ucsf.edu', state: 'CA', city: 'San Francisco', campus: 'San Francisco' },

  // California State University System
  { name: 'California State University, Fullerton', domain: 'fullerton.edu', state: 'CA', city: 'Fullerton', campus: 'Fullerton' },
  { name: 'California State University, Long Beach', domain: 'csulb.edu', state: 'CA', city: 'Long Beach', campus: 'Long Beach' },
  { name: 'California State University, Northridge', domain: 'csun.edu', state: 'CA', city: 'Northridge', campus: 'Northridge' },
  { name: 'San Diego State University', domain: 'sdsu.edu', state: 'CA', city: 'San Diego' },
  { name: 'San Jose State University', domain: 'sjsu.edu', state: 'CA', city: 'San Jose' },
  { name: 'San Francisco State University', domain: 'sfsu.edu', state: 'CA', city: 'San Francisco' },
  { name: 'California State Polytechnic University, Pomona', domain: 'cpp.edu', state: 'CA', city: 'Pomona', campus: 'Pomona' },
  { name: 'California Polytechnic State University, San Luis Obispo', domain: 'calpoly.edu', state: 'CA', city: 'San Luis Obispo' },
  { name: 'California State University, Sacramento', domain: 'csus.edu', state: 'CA', city: 'Sacramento', campus: 'Sacramento' },
  { name: 'California State University, Fresno', domain: 'csufresno.edu', state: 'CA', city: 'Fresno', campus: 'Fresno' },
  { name: 'California State University, Los Angeles', domain: 'calstatela.edu', state: 'CA', city: 'Los Angeles', campus: 'Los Angeles' },
  { name: 'California State University, East Bay', domain: 'csueastbay.edu', state: 'CA', city: 'Hayward', campus: 'East Bay' },
  { name: 'California State University, San Bernardino', domain: 'csusb.edu', state: 'CA', city: 'San Bernardino', campus: 'San Bernardino' },
  { name: 'California State University, Chico', domain: 'csuchico.edu', state: 'CA', city: 'Chico', campus: 'Chico' },
  { name: 'Humboldt State University', domain: 'humboldt.edu', state: 'CA', city: 'Arcata' },
  { name: 'Sonoma State University', domain: 'sonoma.edu', state: 'CA', city: 'Rohnert Park' },
  { name: 'California State University, Monterey Bay', domain: 'csumb.edu', state: 'CA', city: 'Seaside', campus: 'Monterey Bay' },
  { name: 'California State University, San Marcos', domain: 'csusm.edu', state: 'CA', city: 'San Marcos', campus: 'San Marcos' },

  // SUNY System
  { name: 'Stony Brook University', domain: 'stonybrook.edu', state: 'NY', city: 'Stony Brook' },
  { name: 'University at Buffalo', domain: 'buffalo.edu', state: 'NY', city: 'Buffalo' },
  { name: 'University at Albany', domain: 'albany.edu', state: 'NY', city: 'Albany' },
  { name: 'Binghamton University', domain: 'binghamton.edu', state: 'NY', city: 'Binghamton' },
  { name: 'SUNY New Paltz', domain: 'newpaltz.edu', state: 'NY', city: 'New Paltz' },
  { name: 'SUNY Geneseo', domain: 'geneseo.edu', state: 'NY', city: 'Geneseo' },
  { name: 'SUNY Oswego', domain: 'oswego.edu', state: 'NY', city: 'Oswego' },
  { name: 'SUNY Oneonta', domain: 'oneonta.edu', state: 'NY', city: 'Oneonta' },
  { name: 'SUNY Cortland', domain: 'cortland.edu', state: 'NY', city: 'Cortland' },
  { name: 'SUNY Fredonia', domain: 'fredonia.edu', state: 'NY', city: 'Fredonia' },
  { name: 'SUNY Plattsburgh', domain: 'plattsburgh.edu', state: 'NY', city: 'Plattsburgh' },
  { name: 'SUNY Brockport', domain: 'brockport.edu', state: 'NY', city: 'Brockport' },
  { name: 'SUNY Potsdam', domain: 'potsdam.edu', state: 'NY', city: 'Potsdam' },
  { name: 'SUNY Purchase', domain: 'purchase.edu', state: 'NY', city: 'Purchase' },

  // University of Washington System
  { name: 'University of Washington - Seattle', domain: 'washington.edu', state: 'WA', city: 'Seattle', campus: 'Seattle' },
  { name: 'University of Washington - Bothell', domain: 'uwb.edu', state: 'WA', city: 'Bothell', campus: 'Bothell' },
  { name: 'University of Washington - Tacoma', domain: 'tacoma.uw.edu', state: 'WA', city: 'Tacoma', campus: 'Tacoma' },
  { name: 'Washington State University', domain: 'wsu.edu', state: 'WA', city: 'Pullman' },
  { name: 'Washington State University - Vancouver', domain: 'vancouver.wsu.edu', state: 'WA', city: 'Vancouver', campus: 'Vancouver' },
  { name: 'Washington State University - Tri-Cities', domain: 'tricities.wsu.edu', state: 'WA', city: 'Richland', campus: 'Tri-Cities' },

  // University of Texas System
  { name: 'University of Texas at Austin', domain: 'utexas.edu', state: 'TX', city: 'Austin', campus: 'Austin' },
  { name: 'University of Texas at Dallas', domain: 'utdallas.edu', state: 'TX', city: 'Richardson', campus: 'Dallas' },
  { name: 'University of Texas at San Antonio', domain: 'utsa.edu', state: 'TX', city: 'San Antonio', campus: 'San Antonio' },
  { name: 'University of Texas at Arlington', domain: 'uta.edu', state: 'TX', city: 'Arlington', campus: 'Arlington' },
  { name: 'University of Texas at El Paso', domain: 'utep.edu', state: 'TX', city: 'El Paso', campus: 'El Paso' },
  { name: 'University of Texas Rio Grande Valley', domain: 'utrgv.edu', state: 'TX', city: 'Edinburg', campus: 'Rio Grande Valley' },
  { name: 'Texas A&M University', domain: 'tamu.edu', state: 'TX', city: 'College Station' },
  { name: 'Texas A&M University - Commerce', domain: 'tamuc.edu', state: 'TX', city: 'Commerce', campus: 'Commerce' },
  { name: 'Texas A&M University - Corpus Christi', domain: 'tamucc.edu', state: 'TX', city: 'Corpus Christi', campus: 'Corpus Christi' },
  { name: 'Texas Tech University', domain: 'ttu.edu', state: 'TX', city: 'Lubbock' },
  { name: 'Texas State University', domain: 'txstate.edu', state: 'TX', city: 'San Marcos' },
  { name: 'University of Houston', domain: 'uh.edu', state: 'TX', city: 'Houston' },
  { name: 'University of Houston - Clear Lake', domain: 'uhcl.edu', state: 'TX', city: 'Houston', campus: 'Clear Lake' },
  { name: 'University of Houston - Downtown', domain: 'uhd.edu', state: 'TX', city: 'Houston', campus: 'Downtown' },
  { name: 'University of North Texas', domain: 'unt.edu', state: 'TX', city: 'Denton' },

  // Big Ten / Major State Universities
  { name: 'University of Michigan', domain: 'umich.edu', state: 'MI', city: 'Ann Arbor' },
  { name: 'University of Michigan - Dearborn', domain: 'umd.umich.edu', state: 'MI', city: 'Dearborn', campus: 'Dearborn' },
  { name: 'University of Michigan - Flint', domain: 'umflint.edu', state: 'MI', city: 'Flint', campus: 'Flint' },
  { name: 'Michigan State University', domain: 'msu.edu', state: 'MI', city: 'East Lansing' },
  { name: 'Ohio State University', domain: 'osu.edu', state: 'OH', city: 'Columbus' },
  { name: 'Penn State University', domain: 'psu.edu', state: 'PA', city: 'University Park' },
  { name: 'Penn State University - Harrisburg', domain: 'harrisburg.psu.edu', state: 'PA', city: 'Harrisburg', campus: 'Harrisburg' },
  { name: 'Penn State University - Erie', domain: 'behrend.psu.edu', state: 'PA', city: 'Erie', campus: 'Erie' },
  { name: 'University of Wisconsin - Madison', domain: 'wisc.edu', state: 'WI', city: 'Madison', campus: 'Madison' },
  { name: 'University of Wisconsin - Milwaukee', domain: 'uwm.edu', state: 'WI', city: 'Milwaukee', campus: 'Milwaukee' },
  { name: 'University of Wisconsin - La Crosse', domain: 'uwlax.edu', state: 'WI', city: 'La Crosse', campus: 'La Crosse' },
  { name: 'University of Minnesota - Twin Cities', domain: 'umn.edu', state: 'MN', city: 'Minneapolis', campus: 'Twin Cities' },
  { name: 'University of Minnesota - Duluth', domain: 'd.umn.edu', state: 'MN', city: 'Duluth', campus: 'Duluth' },
  { name: 'University of Iowa', domain: 'uiowa.edu', state: 'IA', city: 'Iowa City' },
  { name: 'Iowa State University', domain: 'iastate.edu', state: 'IA', city: 'Ames' },
  { name: 'University of Illinois Urbana-Champaign', domain: 'illinois.edu', state: 'IL', city: 'Champaign', campus: 'Urbana-Champaign' },
  { name: 'University of Illinois Chicago', domain: 'uic.edu', state: 'IL', city: 'Chicago', campus: 'Chicago' },
  { name: 'Indiana University Bloomington', domain: 'iu.edu', state: 'IN', city: 'Bloomington', campus: 'Bloomington' },
  { name: 'Indiana University - Purdue University Indianapolis', domain: 'iupui.edu', state: 'IN', city: 'Indianapolis', campus: 'Indianapolis' },
  { name: 'Purdue University', domain: 'purdue.edu', state: 'IN', city: 'West Lafayette' },
  { name: 'Purdue University - Fort Wayne', domain: 'pfw.edu', state: 'IN', city: 'Fort Wayne', campus: 'Fort Wayne' },
  { name: 'University of Nebraska - Lincoln', domain: 'unl.edu', state: 'NE', city: 'Lincoln', campus: 'Lincoln' },
  { name: 'University of Nebraska - Omaha', domain: 'unomaha.edu', state: 'NE', city: 'Omaha', campus: 'Omaha' },
  { name: 'University of Maryland, College Park', domain: 'umd.edu', state: 'MD', city: 'College Park', campus: 'College Park' },
  { name: 'University of Maryland, Baltimore County', domain: 'umbc.edu', state: 'MD', city: 'Baltimore', campus: 'Baltimore County' },
  { name: 'Rutgers University - New Brunswick', domain: 'rutgers.edu', state: 'NJ', city: 'New Brunswick', campus: 'New Brunswick' },
  { name: 'Rutgers University - Newark', domain: 'newark.rutgers.edu', state: 'NJ', city: 'Newark', campus: 'Newark' },
  { name: 'Rutgers University - Camden', domain: 'camden.rutgers.edu', state: 'NJ', city: 'Camden', campus: 'Camden' },

  // Other Major State Universities
  { name: 'Arizona State University', domain: 'asu.edu', state: 'AZ', city: 'Tempe' },
  { name: 'Arizona State University - Downtown Phoenix', domain: 'asu.edu', state: 'AZ', city: 'Phoenix', campus: 'Downtown Phoenix' },
  { name: 'Arizona State University - West', domain: 'asu.edu', state: 'AZ', city: 'Glendale', campus: 'West' },
  { name: 'Arizona State University - Polytechnic', domain: 'asu.edu', state: 'AZ', city: 'Mesa', campus: 'Polytechnic' },
  { name: 'University of Arizona', domain: 'arizona.edu', state: 'AZ', city: 'Tucson' },
  { name: 'Northern Arizona University', domain: 'nau.edu', state: 'AZ', city: 'Flagstaff' },
  { name: 'University of Colorado Boulder', domain: 'colorado.edu', state: 'CO', city: 'Boulder', campus: 'Boulder' },
  { name: 'University of Colorado Denver', domain: 'ucdenver.edu', state: 'CO', city: 'Denver', campus: 'Denver' },
  { name: 'University of Colorado Colorado Springs', domain: 'uccs.edu', state: 'CO', city: 'Colorado Springs', campus: 'Colorado Springs' },
  { name: 'Colorado State University', domain: 'colostate.edu', state: 'CO', city: 'Fort Collins' },
  { name: 'University of Florida', domain: 'ufl.edu', state: 'FL', city: 'Gainesville' },
  { name: 'Florida State University', domain: 'fsu.edu', state: 'FL', city: 'Tallahassee' },
  { name: 'University of Central Florida', domain: 'ucf.edu', state: 'FL', city: 'Orlando' },
  { name: 'University of South Florida', domain: 'usf.edu', state: 'FL', city: 'Tampa' },
  { name: 'Florida International University', domain: 'fiu.edu', state: 'FL', city: 'Miami' },
  { name: 'Florida Atlantic University', domain: 'fau.edu', state: 'FL', city: 'Boca Raton' },
  { name: 'University of Georgia', domain: 'uga.edu', state: 'GA', city: 'Athens' },
  { name: 'Georgia State University', domain: 'gsu.edu', state: 'GA', city: 'Atlanta' },
  { name: 'University of Virginia', domain: 'virginia.edu', state: 'VA', city: 'Charlottesville' },
  { name: 'Virginia Tech', domain: 'vt.edu', state: 'VA', city: 'Blacksburg' },
  { name: 'Virginia Commonwealth University', domain: 'vcu.edu', state: 'VA', city: 'Richmond' },
  { name: 'James Madison University', domain: 'jmu.edu', state: 'VA', city: 'Harrisonburg' },
  { name: 'Old Dominion University', domain: 'odu.edu', state: 'VA', city: 'Norfolk' },
  { name: 'University of North Carolina at Chapel Hill', domain: 'unc.edu', state: 'NC', city: 'Chapel Hill' },
  { name: 'North Carolina State University', domain: 'ncsu.edu', state: 'NC', city: 'Raleigh' },
  { name: 'University of North Carolina at Charlotte', domain: 'charlotte.edu', state: 'NC', city: 'Charlotte', campus: 'Charlotte' },
  { name: 'East Carolina University', domain: 'ecu.edu', state: 'NC', city: 'Greenville' },
  { name: 'Appalachian State University', domain: 'appstate.edu', state: 'NC', city: 'Boone' },
  { name: 'University of South Carolina', domain: 'sc.edu', state: 'SC', city: 'Columbia' },
  { name: 'Clemson University', domain: 'clemson.edu', state: 'SC', city: 'Clemson' },
  { name: 'University of Tennessee, Knoxville', domain: 'utk.edu', state: 'TN', city: 'Knoxville' },
  { name: 'University of Kentucky', domain: 'uky.edu', state: 'KY', city: 'Lexington' },
  { name: 'University of Louisville', domain: 'louisville.edu', state: 'KY', city: 'Louisville' },
  { name: 'University of Alabama', domain: 'ua.edu', state: 'AL', city: 'Tuscaloosa' },
  { name: 'University of Alabama at Birmingham', domain: 'uab.edu', state: 'AL', city: 'Birmingham', campus: 'Birmingham' },
  { name: 'Auburn University', domain: 'auburn.edu', state: 'AL', city: 'Auburn' },
  { name: 'University of Mississippi', domain: 'olemiss.edu', state: 'MS', city: 'Oxford' },
  { name: 'Mississippi State University', domain: 'msstate.edu', state: 'MS', city: 'Starkville' },
  { name: 'Louisiana State University', domain: 'lsu.edu', state: 'LA', city: 'Baton Rouge' },
  { name: 'University of Arkansas', domain: 'uark.edu', state: 'AR', city: 'Fayetteville' },
  { name: 'University of Missouri', domain: 'missouri.edu', state: 'MO', city: 'Columbia' },
  { name: 'University of Kansas', domain: 'ku.edu', state: 'KS', city: 'Lawrence' },
  { name: 'Kansas State University', domain: 'k-state.edu', state: 'KS', city: 'Manhattan' },
  { name: 'University of Oklahoma', domain: 'ou.edu', state: 'OK', city: 'Norman' },
  { name: 'Oklahoma State University', domain: 'okstate.edu', state: 'OK', city: 'Stillwater' },
  { name: 'University of Oregon', domain: 'uoregon.edu', state: 'OR', city: 'Eugene' },
  { name: 'Oregon State University', domain: 'oregonstate.edu', state: 'OR', city: 'Corvallis' },
  { name: 'Portland State University', domain: 'pdx.edu', state: 'OR', city: 'Portland' },
  { name: 'University of Utah', domain: 'utah.edu', state: 'UT', city: 'Salt Lake City' },
  { name: 'Utah State University', domain: 'usu.edu', state: 'UT', city: 'Logan' },
  { name: 'University of Nevada, Las Vegas', domain: 'unlv.edu', state: 'NV', city: 'Las Vegas' },
  { name: 'University of Nevada, Reno', domain: 'unr.edu', state: 'NV', city: 'Reno' },
  { name: 'University of New Mexico', domain: 'unm.edu', state: 'NM', city: 'Albuquerque' },
  { name: 'New Mexico State University', domain: 'nmsu.edu', state: 'NM', city: 'Las Cruces' },
  { name: 'University of Hawaii at Manoa', domain: 'hawaii.edu', state: 'HI', city: 'Honolulu' },
  { name: 'University of Alaska Fairbanks', domain: 'uaf.edu', state: 'AK', city: 'Fairbanks' },
  { name: 'West Virginia University', domain: 'wvu.edu', state: 'WV', city: 'Morgantown' },
  { name: 'University of Pittsburgh', domain: 'pitt.edu', state: 'PA', city: 'Pittsburgh' },
  { name: 'University of Massachusetts Amherst', domain: 'umass.edu', state: 'MA', city: 'Amherst' },
  { name: 'University of Massachusetts Boston', domain: 'umb.edu', state: 'MA', city: 'Boston', campus: 'Boston' },
  { name: 'University of Massachusetts Lowell', domain: 'uml.edu', state: 'MA', city: 'Lowell', campus: 'Lowell' },
  { name: 'University of Connecticut', domain: 'uconn.edu', state: 'CT', city: 'Storrs' },
  { name: 'University of Rhode Island', domain: 'uri.edu', state: 'RI', city: 'Kingston' },
  { name: 'University of Vermont', domain: 'uvm.edu', state: 'VT', city: 'Burlington' },
  { name: 'University of New Hampshire', domain: 'unh.edu', state: 'NH', city: 'Durham' },
  { name: 'University of Maine', domain: 'umaine.edu', state: 'ME', city: 'Orono' },
  { name: 'University of Delaware', domain: 'udel.edu', state: 'DE', city: 'Newark' },
]

// Expand common abbreviations
export function expandAbbreviation(query: string): string | null {
  const lower = query.toLowerCase().trim()
  return abbreviations[lower] || null
}

// Filter universities based on search query
export function filterUniversities(query: string): University[] {
  if (!query || query.length < 2) return []
  
  const lower = query.toLowerCase().trim()
  
  // Check for abbreviation first
  const expanded = expandAbbreviation(lower)
  if (expanded) {
    return universities.filter(u => 
      u.name.toLowerCase().includes(expanded.toLowerCase())
    ).slice(0, 8)
  }
  
  // Split into words for multi-word matching
  const words = lower.split(/\s+/).filter(w => w.length > 0)
  
  return universities
    .filter(uni => {
      const nameLower = uni.name.toLowerCase()
      const cityLower = uni.city.toLowerCase()
      const stateLower = uni.state.toLowerCase()
      
      // Check if all words match somewhere
      return words.every(word => 
        nameLower.includes(word) || 
        cityLower.includes(word) || 
        stateLower.includes(word) ||
        (uni.campus && uni.campus.toLowerCase().includes(word))
      )
    })
    .sort((a, b) => {
      // Prioritize exact matches at start of name
      const aStartMatch = a.name.toLowerCase().startsWith(lower) ? 0 : 1
      const bStartMatch = b.name.toLowerCase().startsWith(lower) ? 0 : 1
      if (aStartMatch !== bStartMatch) return aStartMatch - bStartMatch
      
      // Then by name length (shorter = more likely what they want)
      return a.name.length - b.name.length
    })
    .slice(0, 10)
}
